import type { ToolDefinition } from "./types";

export const builtInTools = [
  {
    id: "chatgpt",
    name: "ChatGPT",
    url: "https://chatgpt.com/",
    icon: "/logos/chatgpt.svg",
    iconTone: "adaptive",
    fallback: "C",
    category: "chat",
    aliases: ["openai", "gpt"],
    tags: ["writing", "reasoning", "code"],
  },
  {
    id: "claude",
    name: "Claude",
    url: "https://claude.ai/",
    icon: "/logos/claude.svg",
    iconTone: "native",
    fallback: "C",
    category: "chat",
    aliases: ["anthropic"],
    tags: ["writing", "reasoning", "artifacts"],
  },
  {
    id: "gemini",
    name: "Gemini",
    url: "https://gemini.google.com/",
    icon: "/logos/gemini.svg",
    iconTone: "color",
    fallback: "G",
    category: "chat",
    aliases: ["google ai", "bard"],
    tags: ["chat", "multimodal", "google"],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    url: "https://chat.deepseek.com/",
    icon: "/logos/deepseek.svg",
    iconTone: "color",
    fallback: "D",
    category: "chat",
    aliases: ["deep seek"],
    tags: ["chat", "reasoning", "code"],
  },
  {
    id: "grok",
    name: "Grok",
    url: "https://grok.com/",
    icon: "/logos/grok.svg",
    iconTone: "color",
    iconFrame: "app",
    fallback: "G",
    category: "chat",
    aliases: ["xai", "x ai"],
    tags: ["chat", "social", "research"],
  },
  {
    id: "midjourney",
    name: "Midjourney",
    url: "https://www.midjourney.com/",
    icon: "/logos/midjourney.svg",
    iconTone: "adaptive",
    fallback: "M",
    category: "create",
    subcategory: "image",
    aliases: ["mj"],
    tags: ["image", "art", "design"],
  },
  {
    id: "runway",
    name: "Runway",
    url: "https://app.runwayml.com/",
    icon: "/logos/runway.svg",
    iconTone: "adaptive",
    fallback: "R",
    category: "create",
    subcategory: "video",
    aliases: ["runwayml"],
    tags: ["video", "image", "editing"],
  },
  {
    id: "kling",
    name: "Kling AI",
    url: "https://kling.ai/app/",
    icon: "/logos/kling.svg",
    iconTone: "color",
    fallback: "K",
    category: "create",
    subcategory: "video",
    aliases: ["kling", "kuaishou"],
    tags: ["video", "motion", "image"],
  },
  {
    id: "cursor",
    name: "Cursor",
    url: "https://cursor.com/",
    icon: "/logos/cursor.svg",
    iconTone: "adaptive",
    iconFrame: "app",
    fallback: "C",
    category: "code",
    aliases: ["editor", "ide"],
    tags: ["code", "developer", "agent"],
  },
  {
    id: "copilot",
    name: "GitHub Copilot",
    url: "https://github.com/copilot",
    icon: "/logos/copilot.svg",
    iconTone: "adaptive",
    fallback: "G",
    category: "code",
    aliases: ["copilot", "github", "gh"],
    tags: ["code", "developer", "autocomplete"],
  },
  {
    id: "codex",
    name: "Codex",
    url: "https://openai.com/codex/",
    icon: "/logos/codex.svg",
    iconTone: "native",
    iconFrame: "app",
    fallback: "C",
    category: "code",
    aliases: ["openai codex", "coding agent"],
    tags: ["code", "agent", "terminal"],
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    url: "https://huggingface.co/",
    icon: "/logos/huggingface.svg",
    iconTone: "color",
    fallback: "H",
    category: "explore",
    subcategory: "platform",
    aliases: ["hf", "huggingface"],
    tags: ["models", "datasets", "spaces"],
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    url: "https://openrouter.ai/chat",
    icon: "/logos/openrouter.png",
    iconTone: "color",
    iconFrame: "app",
    fallback: "O",
    category: "explore",
    subcategory: "platform",
    aliases: ["router", "model router"],
    tags: ["models", "api", "routing"],
  },
  {
    id: "notebooklm",
    name: "NotebookLM",
    url: "https://notebooklm.google.com/",
    icon: "/logos/notebooklm.svg",
    iconTone: "adaptive",
    fallback: "N",
    category: "explore",
    subcategory: "research",
    aliases: ["notebooklm", "notebook", "google notebook"],
    tags: ["documents", "sources", "notes", "research"],
  },
] as const satisfies readonly ToolDefinition[];
